# SQL Review Learning Demo - 主配置文件

# 服务器配置
server:
  port: 8080
  mode: "debug"  # debug, release
  cors:
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["Content-Type", "Authorization"]

# 数据库配置
database:
  pool:
    max_open_conns: 10
    max_idle_conns: 5
    conn_max_lifetime: "1h"
  connection_timeout: "5s"

# 日志配置
logging:
  level: "info"    # debug, info, warn, error
  format: "text"   # text, json